### ISSUE TITLE
Low contrast social icons on GitHub Dark Theme

### ISSUE THREAD

**Issue by vikasganiga05** [iamdevvalecha/iamdevvalecha#2]
The social icons contrast is low, it's hard to see in GitHub Dark mode. Best to use colored icons which will easily visible in both dark and light mode.

#### Screenshot

![image](https://user-images.githubusercontent.com/74750414/116677964-6c44d080-a9c6-11eb-9197-b0b369c8f47d.png)

**Comment by iamdevvalecha** [comment]
i am not good at css. if possiable please fix this.
@vikasganiga05

**Comment by vikasganiga05** [comment]
> if possiable please fix this.
> @vikasganiga05

Yeah! sure. I will fix this.
